name: review-lassonde
description: Review system for courses at Lassonde using Flutter, Firebase and Selenium.

version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    
    #Firebase
    firebase_core: ^0.4.0+9
    cloud_firestore: ^0.12.9+5

    #Bottom - Navbar
    #google_nav_bar: ^2.1.0
    #line_icons: ^0.2.0

    #Badges
    badges: ^1.1.1

    rename: ^1.2.0

    cupertino_icons: ^0.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_launcher_icons: "^0.7.3"

flutter_icons:
    image_path: "assets/icons/logo.png"
    android: true
    ios: true

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    fonts:
        - family: Avenir
          fonts:
              - asset: assets/fonts/Avenir-Medium.ttf
              - asset: assets/fonts/Avenir-Black.ttf
              - asset: assets/fonts/Avenir-Light.ttf
              - asset: assets/fonts/Avenir-Heavy.ttf
        #Custom Icons
        - family: CustomIcons
          fonts:
              - asset: assets/icons/CustomIcons.ttf
